
package jws.com.sitech.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MainServicePortType", targetNamespace = "http://ws.sitech.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MainServicePortType {


    /**
     * 
     * @param svcCont
     */
    @WebMethod
    @RequestWrapper(localName = "callService", targetNamespace = "http://ws.sitech.com", className = "com.sitech.ws.CallService")
    @ResponseWrapper(localName = "callServiceResponse", targetNamespace = "http://ws.sitech.com", className = "com.sitech.ws.CallServiceResponse")
    public void callService(
        @WebParam(name = "SvcCont", targetNamespace = "http://ws.sitech.com", mode = WebParam.Mode.INOUT)
        Holder<String> svcCont);

}
